# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0005_auto_20180503_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_link',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
